export const FS_EXTENSIONS = {
  FONT: 'woff2',
  PAGE: 'html',
  STYLE: 'css',
  TEMPLATE_PRIMARY: 'njk',
};

export const FS_DIRS = {
  ASSETS: 'assets',
  DATA: 'data',
  DIST: 'dist',
  FONTS: 'fonts',
  INCLUDES: 'includes',
  LAYOUTS: 'layouts',
  SRC: 'src',
  STYLES: 'styles',
};

export const FS_FILES = {
  ALL: `*.{${FS_EXTENSIONS.STYLE},${FS_EXTENSIONS.FONT}}`,
  FONTS: `*.${FS_EXTENSIONS.FONT}`,
  INDEX_STYLE: `index.${FS_EXTENSIONS.STYLE}`,
  MANIFEST: 'manifest.json',
  PAGES: `*.${FS_EXTENSIONS.PAGE}`,
  STYLES: `*.${FS_EXTENSIONS.STYLE}`,
};

export const FS_PATHS = {
  DIST_ASSETS_FONTS: `${FS_DIRS.DIST}/${FS_DIRS.ASSETS}/${FS_DIRS.FONTS}`,
  DIST_ASSETS_STYLES: `${FS_DIRS.DIST}/${FS_DIRS.ASSETS}/${FS_DIRS.STYLES}`,
  DIST_ASSETS: `${FS_DIRS.DIST}/${FS_DIRS.ASSETS}`,
  ELEVENTY: 'node_modules/.bin/eleventy',
  SRC_ASSETS_FONTS: `${FS_DIRS.SRC}/${FS_DIRS.ASSETS}/${FS_DIRS.FONTS}`,
  SRC_ASSETS_STYLES: `${FS_DIRS.SRC}/${FS_DIRS.ASSETS}/${FS_DIRS.STYLES}`,
  SRC_ASSETS: `${FS_DIRS.SRC}/${FS_DIRS.ASSETS}`,
};

export const FS_CONTENT = {
  DIST_ASSETS_DEEP_ALL: `./${FS_PATHS.DIST_ASSETS}/**/${FS_FILES.ALL}`,
  DIST_ASSETS_MANIFEST: `./${FS_PATHS.DIST_ASSETS}/${FS_FILES.MANIFEST}`,
  DIST_DEEP_PAGES: `./${FS_DIRS.DIST}/**/${FS_FILES.PAGES}`,
  SRC_ASSETS_DEEP_STYLES: `./${FS_PATHS.SRC_ASSETS_STYLES}/**/${FS_FILES.STYLES}`,
  SRC_ASSETS_FONTS: `./${FS_PATHS.SRC_ASSETS_FONTS}/${FS_FILES.FONTS}`,
  SRC_ASSETS_STYLES_INDEX: `./${FS_PATHS.SRC_ASSETS_STYLES}/${FS_FILES.INDEX_STYLE}`,
  SRC_ASSETS_STYLES: `./${FS_PATHS.SRC_ASSETS_STYLES}/${FS_FILES.STYLES}`,
};

export const FS_COMMANDS = {
  ESM: 'node -r esm',
};

export const FS_FLAGS = {
  ELEVENTY_SERVE: '--serve --quiet',
};
